/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        'secondary-container': 'var(--md-secondary-container)',
        'tertiary-fixed-dim': 'var(--md-tertiary-fixed-dim)',
        'on-primary-fixed-variant': 'var(--md-on-primary-fixed-variant)',
        'primary-container': 'var(--md-primary-container)',
        'surface-dim': 'var(--md-surface-dim)',
        'error-container': 'var(--md-error-container)',
        'on-error-container': 'var(--md-on-error-container)',
        'primary-fixed': 'var(--md-primary-fixed)',
        'tertiary-dim': 'var(--md-tertiary-dim)',
        'surface-container-high': 'var(--md-surface-container-high)',
        'error-dim': 'var(--md-error-dim)',
        background: 'var(--md-background)',
        'surface-bright': 'var(--md-surface-bright)',
        outline: 'var(--md-outline)',
        'on-primary-container': 'var(--md-on-primary-container)',
        error: 'var(--md-error)',
        'on-secondary-container': 'var(--md-on-secondary-container)',
        'on-primary-fixed': 'var(--md-on-primary-fixed)',
        'tertiary-fixed': 'var(--md-tertiary-fixed)',
        'secondary-fixed': 'var(--md-secondary-fixed)',
        'inverse-on-surface': 'var(--md-inverse-on-surface)',
        'on-tertiary-fixed': 'var(--md-on-tertiary-fixed)',
        tertiary: 'var(--md-tertiary)',
        'surface-tint': 'var(--md-surface-tint)',
        'outline-variant': 'var(--md-outline-variant)',
        'on-error': 'var(--md-on-error)',
        'on-surface-variant': 'var(--md-on-surface-variant)',
        'surface-container-lowest': 'var(--md-surface-container-lowest)',
        'on-tertiary': 'var(--md-on-tertiary)',
        primary: 'var(--md-primary)',
        'on-secondary-fixed': 'var(--md-on-secondary-fixed)',
        'on-background': 'var(--md-on-background)',
        'inverse-primary': 'var(--md-inverse-primary)',
        'inverse-surface': 'var(--md-inverse-surface)',
        'secondary-dim': 'var(--md-secondary-dim)',
        'on-primary': 'var(--md-on-primary)',
        'on-tertiary-fixed-variant': 'var(--md-on-tertiary-fixed-variant)',
        'primary-fixed-dim': 'var(--md-primary-fixed-dim)',
        'tertiary-container': 'var(--md-tertiary-container)',
        secondary: 'var(--md-secondary)',
        'primary-dim': 'var(--md-primary-dim)',
        'surface-container': 'var(--md-surface-container)',
        'on-secondary': 'var(--md-on-secondary)',
        surface: 'var(--md-surface)',
        'on-surface': 'var(--md-on-surface)',
        'surface-container-highest': 'var(--md-surface-container-highest)',
        'on-secondary-fixed-variant': 'var(--md-on-secondary-fixed-variant)',
        'on-tertiary-container': 'var(--md-on-tertiary-container)',
        'secondary-fixed-dim': 'var(--md-secondary-fixed-dim)',
        'surface-variant': 'var(--md-surface-variant)',
        'surface-container-low': 'var(--md-surface-container-low)',
      },
      fontFamily: {
        headline: ['Epilogue', 'Inter', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
        label: ['Space Grotesk', 'Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
